pictech.api.base-url=http://example.com
pictech.api.key=pic_9DD88A6D
pictech.api.secret=XXXXXXXXXXXXXXXX
server.port=8080
file.upload-dir=./output
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB